//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICPRO_APP.Serivicios {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serivicios.ServicioSoap")]
    public interface ServicioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultar(string codigoLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarAsync(string codigoLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet tipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tipos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> tiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Crear(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear", ReplyAction="*")]
        System.Threading.Tasks.Task CrearAsync(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Editar(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        System.Threading.Tasks.Task EditarAsync(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar(string codigoLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarAsync(string codigoLibro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : MUSICPRO_APP.Serivicios.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<MUSICPRO_APP.Serivicios.ServicioSoap>, MUSICPRO_APP.Serivicios.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet VerProductos() {
            return base.Channel.VerProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VerProductosAsync() {
            return base.Channel.VerProductosAsync();
        }
        
        public System.Data.DataSet consultar(string codigoLibro) {
            return base.Channel.consultar(codigoLibro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarAsync(string codigoLibro) {
            return base.Channel.consultarAsync(codigoLibro);
        }
        
        public System.Data.DataSet tipos() {
            return base.Channel.tipos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> tiposAsync() {
            return base.Channel.tiposAsync();
        }
        
        public void Crear(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo) {
            base.Channel.Crear(id, nombre, descripcion, imagen, cantidad, cant_min, precio, tipo);
        }
        
        public System.Threading.Tasks.Task CrearAsync(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo) {
            return base.Channel.CrearAsync(id, nombre, descripcion, imagen, cantidad, cant_min, precio, tipo);
        }
        
        public void Editar(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo) {
            base.Channel.Editar(id, nombre, descripcion, imagen, cantidad, cant_min, precio, tipo);
        }
        
        public System.Threading.Tasks.Task EditarAsync(int id, string nombre, string descripcion, string imagen, int cantidad, int cant_min, int precio, string tipo) {
            return base.Channel.EditarAsync(id, nombre, descripcion, imagen, cantidad, cant_min, precio, tipo);
        }
        
        public void Eliminar(string codigoLibro) {
            base.Channel.Eliminar(codigoLibro);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(string codigoLibro) {
            return base.Channel.EliminarAsync(codigoLibro);
        }
    }
}
